# Generated by Django 3.2 on 2024-09-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
